# .github/workflows/weekly-update.yml
#
# Automated weekly data collection for Fantasy Baseball Civil War
# Runs every Monday at 6:00 AM ET (10:00 UTC) to collect the previous week's data
#
# Prerequisites:
# 1. Set up repository secrets (Settings > Secrets and variables > Actions):
#    - YAHOO_CLIENT_ID: Your Yahoo app's client ID
#    - YAHOO_CLIENT_SECRET: Your Yahoo app's client secret  
#    - YAHOO_REFRESH_TOKEN: OAuth refresh token from initial setup
#
# 2. The workflow will:
#    - Check out your repository
#    - Set up Python with required dependencies
#    - Reconstruct oauth2.json from secrets
#    - Run the weekly stats collection script
#    - Commit and push changes back to the repository

name: Weekly Fantasy Baseball Update

on:
  # Scheduled run: Every Monday at 6:00 AM Eastern (10:00 UTC)
  # Adjust the cron schedule as needed for your timezone
  schedule:
    - cron: '0 10 * * 1'  # 10:00 UTC = 6:00 AM ET / 5:00 AM CT
  
  # Allow manual triggering from the Actions tab
  workflow_dispatch:
    inputs:
      week:
        description: 'Specific week to collect (leave empty for auto-detect)'
        required: false
        default: ''

# Permissions needed to push commits
permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # 3. Cache pip dependencies for faster runs
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yahoo_oauth yahoo_fantasy_api pandas
      
      # 5. Create oauth2.json from secrets
      - name: Create OAuth credentials file
        run: |
          cat > oauth2.json << EOF
          {
            "consumer_key": "${{ secrets.YAHOO_CLIENT_ID }}",
            "consumer_secret": "${{ secrets.YAHOO_CLIENT_SECRET }}",
            "refresh_token": "${{ secrets.YAHOO_REFRESH_TOKEN }}",
            "token_type": "bearer"
          }
          EOF
      
      # 6. Run the weekly stats collection
      - name: Collect weekly stats
        run: |
          python collect_weekly_stats.py
        env:
          # Set timezone for accurate week calculations
          TZ: America/New_York
      
      # 7. Commit and push changes
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Add all changed files in the data directory
          git add data/
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            # Get current date for commit message
            DATE=$(date +'%Y-%m-%d')
            git commit -m "📊 Weekly stats update - ${DATE}"
            git push
            echo "Changes committed and pushed successfully"
          fi
      
      # 8. Clean up sensitive files
      - name: Clean up
        if: always()
        run: |
          rm -f oauth2.json
